apiVersion: v1
kind: ConfigMap
metadata:
  name: discountapi
  namespace: default
data:
  DatabaseSettings__ConnectionString: Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;Pooling=true;
  ElasticConfiguration__Uri: http://elasticsearch:9200