apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: discount
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-05-03T14:17:45Z"
  generation: 5
  labels:
    app.kubernetes.io/instance: discount
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: discount-grpc
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: discount-grpc-0.1.0
  name: discountapi
  namespace: default
  resourceVersion: "15960"
  uid: a9573bd5-03b9-4fb6-a981-566cadb0cb56
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: discount-grpc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: discount
        app.kubernetes.io/name: discount-grpc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DatabaseSettings__ConnectionString
          valueFrom:
            configMapKeyRef:
              name: discountapi
              key: DatabaseSettings__ConnectionString
        - name: ElasticConfiguration__Uri
          valueFrom:
            configMapKeyRef:
              name: discountapi
              key: ElasticConfiguration__Uri
        envFrom:
        - configMapRef:
            name: discountapi
        image: slowey/discountapi:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health/live
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 30
        name: discount-grpc
        ports:
        - name: grpc
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health/ready
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-05-03T14:17:45Z"
    lastUpdateTime: "2025-05-03T14:17:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-05-03T18:12:53Z"
    lastUpdateTime: "2025-05-03T18:19:01Z"
    message: ReplicaSet "discountapi-c685cd7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 5
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
